version:  '3'
services:
  cacher:
     image: "joequant/cacher"
     ports:
       - 3128:3128
       - 3632:3632
       - 3633:3633
     volumes:
       - spool:/var/spool
       - log:/var/log

volumes:
      spool:
      log:
